### ISSUE TITLE
Is there detection code?

### ISSUE THREAD

**Issue by jtlee90** [iamhankai/ghostnet#3]
I saw that there was detection results on the paper.

For the proper re-production of detection results, I'd like to refer your code... but seems not included in this repository.

Is there any other repository for the detection? or not available?

**Comment by iamhankai** [comment]
The detection code is not released yet. We used [mmdetection](https://github.com/open-mmlab/mmdetection) in our experiments. Just replacing the backbone with GhostNet can reproduce the results.

**Comment by jtlee90** [comment]
Thank you for letting me know~!

**Comment by abhigoku10** [comment]
@iamhankai  when can we expect the detection code to be released ??

**Comment by iamhankai** [comment]
@abhigoku10 No exact timeline for the moment.
